version: '3'
services:
  servicio1:
    build: .
    container_name: danyrweb
    restart: always
    ports:
      - 8828:80
    depends_on:
      - servicio2
    volumes: 
      - C:/Users/PC/Desktop/danyrodriguez/vol:/datadrive


  servicio2:
    container_name: danyrdb
    image: mariadb
    restart: always
    ports:
      - 3336:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_PASSWORD=myuserpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser




